RUN pacman -S --needed --noconfirm \
  clang
{%- if parameters.with_omp is sameas true %} \
  openmp
{%- endif %} \
  gcc \
  cmake \
  doxygen \
  gdb \
  valgrind \
  cppcheck
{%- if parameters.with_boost is sameas true %} \
  boost boost-libs
{%- endif %} && \
  pacman -Scc --noconfirm

RUN wget -q https://github.com/linux-test-project/lcov/releases/download/v1.16/lcov-1.16.tar.gz && \
  tar xf lcov-1.16.tar.gz && \
  cp -n lcov-1.16/bin/* /usr/local/bin/ && \
  rm -rf lcov-1.16*