RUN pacman -S --noconfirm \
      clang \
      openmp \
      openmpi \
      gcc \
      cmake \
      make \
      gdb \
      binutils \
      {% if parameters.boost is true %} boost boost-libs {% endif %} && \
    pacman -Scc --noconfirm
