RUN pacman -S --needed --noconfirm \
      clang
      {%- if parameters.with_omp is sameas true %} \
      openmp openmpi
      {%- endif %} \
      gcc \
      cmake \
      make \
      gdb \
      valgrind
      {%- if parameters.with_boost is sameas true %} \
      boost boost-libs
      {%- endif %} && \
    pacman -Scc --noconfirm
