RUN pacman -S --needed --noconfirm \
      clang
      {%- if parameters.with_omp is true %} \
      openmp openmpi
      {%- endif %} \
      gcc \
      cmake \
      make \
      gdb \
      binutils
      {%- if parameters.with_boost is true %} \
      boost boost-libs
      {%- endif %} && \
    pacman -Scc --noconfirm
