ADD settings.json /home/theia/.theia/
ADD .gitconfig /home/theia/

RUN pacman -S --needed --noconfirm \
      python-pip && \
    pacman -Scc --noconfirm
RUN su - theia -c "pip install --user compiledb"
RUN echo "{{ parameters.echo }}"
