RUN apt update && apt install -y -qq \
      curl && \
    rm -rf /var/lib/apt/lists/*

RUN su - theia -c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y" && \
    su - theia -c "rustup default {{ parameters.rust_channel|default('stable') }}" && \
    su - theia -c "rustup component add rust-src rust-docs rust-analysis rustfmt clippy"
    {%- if parameters.rust_channel|default('stable') != "nightly" %} && \
    su - theia -c "rustup component add rls"
    {%- endif %}
    {%- if parameters.with_racer is sameas true %} && \
    su - theia -c "cargo +{{ parameters.rust_channel|default('stable') }} install racer"
    {%- endif %}