RUN pacman -S --noconfirm \
      rustup \
      make \
      gdb \
      binutils && \
    pacman -Scc --noconfirm

RUN su - theia -c "rustup default {{ parameters.rust_channel|default('stable') }}" && \
    su - theia -c "rustup component add rust-src rust-docs rls rust-analysis rustfmt clippy" && \
    su - theia -c "cargo +{{ parameters.rust_channel|default('stable') }} install racer"