RUN apt update && apt install -y -qq \
        python3-pip && \
    pip3 install --upgrade pip && \
    pip3 install python-language-server flake8 autopep8 pylint rope && \
    rm -rf /var/lib/apt/lists/*