app:
  version: "0.0.1"
  license: "Apache-2.0"
  title: "Example Theia Application"
  org: my-org
  base: ubuntu
  base_tag: focal
  dep_version: latest
parameters:
  module:
    echo: "hello world"
build:
  registry: "my-registry.my.org"
modules:
  - pkg-manager
  - rust
  - cpp
  - python
