RUN apt update && apt install -y -qq \
      clang clang-tools clang-format clang-tidy clazy
      {%- if parameters.with_omp is sameas true %} \
      libgomp1 libomp-dev libomp5 libopenmpi-dev libopenmpi3
      {%- endif %} \
      gcc \
      g++ \
      cmake \
      doxygen \
      gdb \
      valgrind
      {%- if parameters.with_boost is sameas true %} \
      libboost-dev libboost-all-dev
      {%- endif %} && \
    rm -rf /var/lib/apt/lists/*

RUN wget -q https://github.com/linux-test-project/lcov/releases/download/v1.15/lcov-1.15.tar.gz && \
    tar xf lcov-1.15.tar.gz && \
    cp -n lcov-1.15/bin/* /usr/local/bin/ && \
    rm -rf lcov-1.15*