FROM archlinux/archlinux:{{ base_tag|default('latest') }}

ARG THEIA_UID=1000

RUN pacman -Syyuu --noconfirm && \
    pacman -S --needed --noconfirm \
      yarn nodejs-lts-erbium npm tar grep awk wget git openssh make gcc python2 vim bash-completion binutils && \
    pacman -Scc --noconfirm && \
    npm config set python /usr/bin/python2 --global && \
    npm config set python /usr/bin/python2

RUN useradd -s /bin/bash -m -d /home/theia -U -u $THEIA_UID -c '' theia && \
    chmod g+rw /home && \
    mkdir -p /home/project && \
    chown -R theia:theia /home/theia && \
    chown -R theia:theia /home/project

{% for s in scripts %}
{{ s }}
{% endfor %}

RUN chown -R theia:theia /home/theia

USER theia
WORKDIR /home/theia
ADD package.json ./package.json

ENV PATH=/home/theia/bin:/home/theia/.local/bin:$PATH

RUN yarn --pure-lockfile && \
    NODE_OPTIONS="--max_old_space_size=4096" yarn theia build && \
    yarn theia download:plugins && \
    yarn --production && \
    yarn autoclean --init && \
    echo *.ts >> .yarnclean && \
    echo *.ts.map >> .yarnclean && \
    echo *.spec.* >> .yarnclean && \
    yarn autoclean --force && \
    yarn cache clean && \
    rm -f .yarnclean

ENV THEIA_DEFAULT_PLUGINS=local-dir:/home/theia/plugins \
    SHELL=/bin/bash \
    VISUAL=vim \
    EDITOR=vim

EXPOSE 3000

ENTRYPOINT [ "node", "/home/theia/src-gen/backend/main.js", "/home/project", "--hostname=0.0.0.0" ]